# Build image
FROM mcr.microsoft.com/dotnet/sdk:6.0 AS build
WORKDIR /src

# Másoljuk át a projekt fájlokat
COPY ["Lakberendezes.csproj", "./"]
RUN dotnet restore

# Másoljuk át a teljes projektet
COPY . .
RUN dotnet publish -c Release -o /app/publish

# Final image
FROM mcr.microsoft.com/dotnet/aspnet:6.0
WORKDIR /app
COPY --from=build /app/publish .
ENTRYPOINT ["dotnet", "Lakberendezes.dll"]