// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;
public class RoomLabTest {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() {
    driver = new ChromeDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  public String waitForWindow(int timeout) {
    try {
      Thread.sleep(timeout);
    } catch (InterruptedException e) {
      e.printStackTrace();
    }
    Set<String> whNow = driver.getWindowHandles();
    Set<String> whThen = (Set<String>) vars.get("window_handles");
    if (whNow.size() > whThen.size()) {
      whNow.removeAll(whThen);
    }
    return whNow.iterator().next();
  }
  @Test
  public void roomLab() {
    // Test name: RoomLab
    // Step # | name | target | value
    // 1 | open | /login | 
    driver.get("https://roomlab-48d26.web.app/login");
    // 2 | setWindowSize | 974x852 | 
    driver.manage().window().setSize(new Dimension(974, 852));
    // 3 | click | css=.form-group:nth-child(1) > .form-input | 
    driver.findElement(By.cssSelector(".form-group:nth-child(1) > .form-input")).click();
    // 4 | click | css=.register-button | 
    driver.findElement(By.cssSelector(".register-button")).click();
    // 5 | mouseOver | css=.register-button | 
    {
      WebElement element = driver.findElement(By.cssSelector(".register-button"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    // 6 | click | css=.form-group:nth-child(1) > .form-input | 
    driver.findElement(By.cssSelector(".form-group:nth-child(1) > .form-input")).click();
    // 7 | type | css=.form-group:nth-child(1) > .form-input | pro
    driver.findElement(By.cssSelector(".form-group:nth-child(1) > .form-input")).sendKeys("pro");
    // 8 | type | css=.form-group:nth-child(2) > .form-input | proba
    driver.findElement(By.cssSelector(".form-group:nth-child(2) > .form-input")).sendKeys("proba");
    // 9 | type | css=.form-group:nth-child(3) > .form-input | liptakreka07@gmail.com
    driver.findElement(By.cssSelector(".form-group:nth-child(3) > .form-input")).sendKeys("liptakreka07@gmail.com");
    // 10 | type | css=.form-group:nth-child(4) > .form-input | kicsikacsA10.
    driver.findElement(By.cssSelector(".form-group:nth-child(4) > .form-input")).sendKeys("kicsikacsA10.");
    // 11 | mouseDown | css=.form-group:nth-child(5) > .form-input | 
    {
      WebElement element = driver.findElement(By.cssSelector(".form-group:nth-child(5) > .form-input"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).clickAndHold().perform();
    }
    // 12 | mouseUp | css=.register-form | 
    {
      WebElement element = driver.findElement(By.cssSelector(".register-form"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).release().perform();
    }
    // 13 | click | css=.register-form | 
    driver.findElement(By.cssSelector(".register-form")).click();
    // 14 | type | css=.form-group:nth-child(5) > .form-input | kicsikacsA10.
    driver.findElement(By.cssSelector(".form-group:nth-child(5) > .form-input")).sendKeys("kicsikacsA10.");
    // 15 | click | css=.form-group:nth-child(6) > .form-input | 
    driver.findElement(By.cssSelector(".form-group:nth-child(6) > .form-input")).click();
    // 16 | type | css=.form-group:nth-child(6) > .form-input | C:\fakepath\elfelejtett.png
    driver.findElement(By.cssSelector(".form-group:nth-child(6) > .form-input")).sendKeys("C:\\fakepath\\elfelejtett.png");
    // 17 | click | css=.register-button | 
    driver.findElement(By.cssSelector(".register-button")).click();
    // 18 | click | css=.form-group:nth-child(1) > .form-input | 
    driver.findElement(By.cssSelector(".form-group:nth-child(1) > .form-input")).click();
    // 19 | type | css=.form-group:nth-child(1) > .form-input | liptakreka07@gmail.com
    driver.findElement(By.cssSelector(".form-group:nth-child(1) > .form-input")).sendKeys("liptakreka07@gmail.com");
    // 20 | type | css=.form-group:nth-child(2) > .form-input | kicsikacsA10.
    driver.findElement(By.cssSelector(".form-group:nth-child(2) > .form-input")).sendKeys("kicsikacsA10.");
    // 21 | sendKeys | css=.form-group:nth-child(2) > .form-input | ${KEY_ENTER}
    driver.findElement(By.cssSelector(".form-group:nth-child(2) > .form-input")).sendKeys(Keys.ENTER);
    // 22 | click | linkText=Kezdj tervezni | 
    driver.findElement(By.linkText("Kezdj tervezni")).click();
    // 23 | mouseOver | linkText=Kezdj tervezni | 
    {
      WebElement element = driver.findElement(By.linkText("Kezdj tervezni"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    // 24 | click | linkText=Kezdőlap | 
    driver.findElement(By.linkText("Kezdőlap")).click();
    // 25 | click | linkText=Tudj meg többet | 
    driver.findElement(By.linkText("Tudj meg többet")).click();
    // 26 | click | css=.cta-button | 
    driver.findElement(By.cssSelector(".cta-button")).click();
    // 27 | click | css=.product-card:nth-child(1) > .buy-btn | 
    driver.findElement(By.cssSelector(".product-card:nth-child(1) > .buy-btn")).click();
    // 28 | mouseOver | css=.product-card:nth-child(1) > .buy-btn | 
    {
      WebElement element = driver.findElement(By.cssSelector(".product-card:nth-child(1) > .buy-btn"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    // 29 | mouseOut | css=.product-card:nth-child(1) > .buy-btn | 
    {
      WebElement element = driver.findElement(By.tagName("body"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element, 0, 0).perform();
    }
    // 30 | click | css=.product-card:nth-child(2) > .buy-btn | 
    driver.findElement(By.cssSelector(".product-card:nth-child(2) > .buy-btn")).click();
    // 31 | mouseOver | css=.product-card:nth-child(2) > .buy-btn | 
    {
      WebElement element = driver.findElement(By.cssSelector(".product-card:nth-child(2) > .buy-btn"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    // 32 | mouseOut | css=.product-card:nth-child(2) > .buy-btn | 
    {
      WebElement element = driver.findElement(By.tagName("body"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element, 0, 0).perform();
    }
    // 33 | mouseDownAt | css=.placed-product:nth-child(3) | 254.75,73.453125
    {
      WebElement element = driver.findElement(By.cssSelector(".placed-product:nth-child(3)"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).clickAndHold().perform();
    }
    // 34 | mouseMoveAt | css=.placed-product:nth-child(3) | 254.75,73.453125
    {
      WebElement element = driver.findElement(By.cssSelector(".placed-product:nth-child(3)"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    // 35 | mouseUpAt | css=.placed-product:nth-child(3) | 254.75,73.453125
    {
      WebElement element = driver.findElement(By.cssSelector(".placed-product:nth-child(3)"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).release().perform();
    }
    // 36 | click | css=.placed-product:nth-child(3) | 
    driver.findElement(By.cssSelector(".placed-product:nth-child(3)")).click();
    // 37 | mouseDownAt | css=.placed-product:nth-child(2) | 241.5,101.953125
    {
      WebElement element = driver.findElement(By.cssSelector(".placed-product:nth-child(2)"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).clickAndHold().perform();
    }
    // 38 | mouseMoveAt | css=.placed-product:nth-child(2) | 241.5,101.953125
    {
      WebElement element = driver.findElement(By.cssSelector(".placed-product:nth-child(2)"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    // 39 | mouseUpAt | css=.placed-product:nth-child(2) | 241.5,101.953125
    {
      WebElement element = driver.findElement(By.cssSelector(".placed-product:nth-child(2)"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).release().perform();
    }
    // 40 | click | css=.placed-product:nth-child(2) | 
    driver.findElement(By.cssSelector(".placed-product:nth-child(2)")).click();
    // 41 | click | css=.save-btn | 
    driver.findElement(By.cssSelector(".save-btn")).click();
    // 42 | click | css=.placed-product:nth-child(2) > .remove-btn > .lucide | 
    driver.findElement(By.cssSelector(".placed-product:nth-child(2) > .remove-btn > .lucide")).click();
    // 43 | click | css=.lucide-x > path:nth-child(1) | 
    driver.findElement(By.cssSelector(".lucide-x > path:nth-child(1)")).click();
    // 44 | click | css=.category-button:nth-child(2) | 
    driver.findElement(By.cssSelector(".category-button:nth-child(2)")).click();
    // 45 | runScript | window.scrollTo(0,0) | 
    js.executeScript("window.scrollTo(0,0)");
    // 46 | click | css=.category-button:nth-child(3) | 
    driver.findElement(By.cssSelector(".category-button:nth-child(3)")).click();
    // 47 | click | css=.category-button:nth-child(4) | 
    driver.findElement(By.cssSelector(".category-button:nth-child(4)")).click();
    // 48 | click | css=.load-btn | 
    driver.findElement(By.cssSelector(".load-btn")).click();
    // 49 | click | linkText=Kezdőlap | 
    driver.findElement(By.linkText("Kezdőlap")).click();
    // 50 | click | linkText=Rólunk | 
    driver.findElement(By.linkText("Rólunk")).click();
    // 51 | click | linkText=Kapcsolat | 
    driver.findElement(By.linkText("Kapcsolat")).click();
    // 52 | click | css=.search-input | 
    driver.findElement(By.cssSelector(".search-input")).click();
    // 53 | click | css=.lucide-moon | 
    driver.findElement(By.cssSelector(".lucide-moon")).click();
    // 54 | click | css=.lucide-sun | 
    driver.findElement(By.cssSelector(".lucide-sun")).click();
    // 55 | click | css=.lucide-shopping-cart | 
    driver.findElement(By.cssSelector(".lucide-shopping-cart")).click();
    // 56 | click | css=.buy-button:nth-child(4) | 
    driver.findElement(By.cssSelector(".buy-button:nth-child(4)")).click();
    // 57 | runScript | window.scrollTo(0,246) | 
    js.executeScript("window.scrollTo(0,246)");
    // 58 | runScript | window.scrollTo(0,0) | 
    js.executeScript("window.scrollTo(0,0)");
    // 59 | click | linkText=Megnézem | 
    vars.put("window_handles", driver.getWindowHandles());
    // 60 | storeWindowHandle | root | 
    driver.findElement(By.linkText("Megnézem")).click();
    // 61 | selectWindow | handle=${win7677} | 
    vars.put("win7677", waitForWindow(2000));
    // 62 | close |  | 
    vars.put("root", driver.getWindowHandle());
    // 63 | selectWindow | handle=${root} | 
    driver.switchTo().window(vars.get("win7677").toString());
    // 64 | click | css=.flex:nth-child(2) .shops | 
    driver.close();
    // 65 | selectWindow | handle=${win2137} | 
    driver.switchTo().window(vars.get("root").toString());
    // 66 | close |  | 
    vars.put("window_handles", driver.getWindowHandles());
    // 67 | selectWindow | handle=${root} | 
    driver.findElement(By.cssSelector(".flex:nth-child(2) .shops")).click();
    // 68 | click | css=.toplanner | 
    vars.put("win2137", waitForWindow(2000));
    // 69 | click | css=.Toastify__close-button path | 
    driver.switchTo().window(vars.get("win2137").toString());
    // 70 | mouseOver | css=.Toastify__close-button path | 
    driver.close();
    // 71 | mouseOut | css=.Toastify__close-button path | 
    driver.switchTo().window(vars.get("root").toString());
    // 72 | click | css=path:nth-child(3) | 
    driver.findElement(By.cssSelector(".toplanner")).click();
    // 73 | click | css=.clear-button:nth-child(5) | 
    driver.findElement(By.cssSelector(".Toastify__close-button path")).click();
    // 74 | click | css=.btn-outline-primary | 
    {
      WebElement element = driver.findElement(By.cssSelector(".Toastify__close-button path"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    // 75 | click | linkText=Beállítások | 
    {
      WebElement element = driver.findElement(By.tagName("body"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element, 0, 0).perform();
    }
    // 76 | mouseOver | linkText=Beállítások | 
    driver.findElement(By.cssSelector("path:nth-child(3)")).click();
    // 77 | mouseOut | linkText=Beállítások | 
    driver.findElement(By.cssSelector(".clear-button:nth-child(5)")).click();
    // 78 | click | css=.btn-outline-primary | 
    driver.findElement(By.cssSelector(".btn-outline-primary")).click();
    // 79 | click | css=input | 
    driver.findElement(By.linkText("Beállítások")).click();
    // 80 | type | css=input | C:\fakepath\email.png
    {
      WebElement element = driver.findElement(By.linkText("Beállítások"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    // 81 | click | css=.profile-upload-container > button | 
    {
      WebElement element = driver.findElement(By.tagName("body"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element, 0, 0).perform();
    }
    // 82 | click | css=.tabs > button:nth-child(2) | 
    driver.findElement(By.cssSelector(".btn-outline-primary")).click();
    // 83 | click | css=.Toastify__close-button path | 
    driver.findElement(By.cssSelector("input")).click();
    // 84 | click | css=input:nth-child(1) | 
    driver.findElement(By.cssSelector("input")).sendKeys("C:\\fakepath\\email.png");
    // 85 | type | css=input:nth-child(1) | kicsikacsA10.
    driver.findElement(By.cssSelector(".profile-upload-container > button")).click();
    // 86 | click | css=input:nth-child(2) | 
    driver.findElement(By.cssSelector(".tabs > button:nth-child(2)")).click();
    // 87 | type | css=input:nth-child(2) | 822870Ma.
    driver.findElement(By.cssSelector(".Toastify__close-button path")).click();
    // 88 | click | css=.settings-btn | 
    driver.findElement(By.cssSelector("input:nth-child(1)")).click();
    // 89 | click | css=.delete-account-btn | 
    driver.findElement(By.cssSelector("input:nth-child(1)")).sendKeys("kicsikacsA10.");
    // 90 | click | css=.delete-confirmation > input | 
    driver.findElement(By.cssSelector("input:nth-child(2)")).click();
    // 91 | type | css=.delete-confirmation > input | proba
    driver.findElement(By.cssSelector("input:nth-child(2)")).sendKeys("822870Ma.");
    // 92 | click | css=.confirm-delete-btn | 
    driver.findElement(By.cssSelector(".settings-btn")).click();
    // 93 | close |  | 
    driver.findElement(By.cssSelector(".delete-account-btn")).click();
    driver.findElement(By.cssSelector(".delete-confirmation > input")).click();
    driver.findElement(By.cssSelector(".delete-confirmation > input")).sendKeys("proba");
    driver.findElement(By.cssSelector(".confirm-delete-btn")).click();
    driver.close();
  }
}
