// <auto-generated />
using System;
using Lakberendezes.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Lakberendezes.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20240921115025_Idcorrection")]
    partial class Idcorrection
    {
        /// <inheritdoc />
        protected  void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("Lakberendezes.Models.Categories", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("id"));

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("id");

                    b.ToTable("kategories");
                });

            modelBuilder.Entity("Lakberendezes.Models.PlanProduct", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("id"));

                    b.Property<string>("position")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("productid")
                        .HasColumnType("int");

                    b.Property<int>("userplanid")
                        .HasColumnType("int");

                    b.HasKey("id");

                    b.HasIndex("productid");

                    b.HasIndex("userplanid");

                    b.ToTable("planproducts");
                });

            modelBuilder.Entity("Lakberendezes.Models.Product", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("id"));

                    b.Property<string>("imageurl")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<decimal>("price")
                        .HasColumnType("decimal(65,30)");

                    b.Property<int>("product_type_id")
                        .HasColumnType("int");

                    b.Property<int>("roomid")
                        .HasColumnType("int");

                    b.Property<int>("shopid")
                        .HasColumnType("int");

                    b.Property<string>("shoplink")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("id");

                    b.HasIndex("product_type_id");

                    b.HasIndex("roomid");

                    b.HasIndex("shopid");

                    b.ToTable("products");
                });

            modelBuilder.Entity("Lakberendezes.Models.ProductType", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("id"));

                    b.Property<int>("categoryid")
                        .HasColumnType("int");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("id");

                    b.HasIndex("categoryid");

                    b.ToTable("producttype");
                });

            modelBuilder.Entity("Lakberendezes.Models.Shops", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("id"));

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("websiteurl")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("id");

                    b.ToTable("shops");
                });

            modelBuilder.Entity("Lakberendezes.Models.User", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("id"));

                    b.Property<string>("PASSWORD_hash")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("datet")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("email")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("fullname")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("id");

                    b.ToTable("users");
                });

            modelBuilder.Entity("Lakberendezes.Models.UserPlans", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("id"));

                    b.Property<DateTime>("createdat")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("plandata")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("userid")
                        .HasColumnType("int");

                    b.HasKey("id");

                    b.HasIndex("userid");

                    b.ToTable("userplan");
                });

            modelBuilder.Entity("Lakberendezes.Models.PlanProduct", b =>
                {
                    b.HasOne("Lakberendezes.Models.Product", "Product")
                        .WithMany("products")
                        .HasForeignKey("productid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Lakberendezes.Models.UserPlans", "Userplans")
                        .WithMany("Products")
                        .HasForeignKey("userplanid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");

                    b.Navigation("Userplans");
                });

            modelBuilder.Entity("Lakberendezes.Models.Product", b =>
                {
                    b.HasOne("Lakberendezes.Models.ProductType", "ProductType")
                        .WithMany("products_ibfk_2")
                        .HasForeignKey("product_type_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Lakberendezes.Models.Categories", "Categories")
                        .WithMany("products_ibfk_3")
                        .HasForeignKey("roomid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Lakberendezes.Models.Shops", "Shops")
                        .WithMany("products_ibfk_1")
                        .HasForeignKey("shopid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Categories");

                    b.Navigation("ProductType");

                    b.Navigation("Shops");
                });

            modelBuilder.Entity("Lakberendezes.Models.ProductType", b =>
                {
                    b.HasOne("Lakberendezes.Models.Categories", "Categories")
                        .WithMany("producttype_ibfk_1")
                        .HasForeignKey("categoryid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Categories");
                });

            modelBuilder.Entity("Lakberendezes.Models.UserPlans", b =>
                {
                    b.HasOne("Lakberendezes.Models.User", "User")
                        .WithMany("plans")
                        .HasForeignKey("userid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Lakberendezes.Models.Categories", b =>
                {
                    b.Navigation("products_ibfk_3");

                    b.Navigation("producttype_ibfk_1");
                });

            modelBuilder.Entity("Lakberendezes.Models.Product", b =>
                {
                    b.Navigation("products");
                });

            modelBuilder.Entity("Lakberendezes.Models.ProductType", b =>
                {
                    b.Navigation("products_ibfk_2");
                });

            modelBuilder.Entity("Lakberendezes.Models.Shops", b =>
                {
                    b.Navigation("products_ibfk_1");
                });

            modelBuilder.Entity("Lakberendezes.Models.User", b =>
                {
                    b.Navigation("plans");
                });

            modelBuilder.Entity("Lakberendezes.Models.UserPlans", b =>
                {
                    b.Navigation("Products");
                });
#pragma warning restore 612, 618
        }
    }
}
